### ISSUE TITLE
Халлоу рашан пипл)0))

### ISSUE THREAD

**Issue by XakerS** [FaigerSYS/superBAR_RUS#1]
Приятно видеть RUS девелопера)

**Comment by FaigerSYS** [comment]
Можно не засорять здесь ничего? :\

**Comment by XakerS** [comment]
Ой ой важная личность...

**Comment by FaigerSYS** [comment]
Не очень. Но мне тут флуд не нужен. Для этого уже есть флудилка.

**Comment by XakerS** [comment]
Где?

**Comment by FaigerSYS** [comment]
#2
