### ISSUE TITLE
Флудилка

### ISSUE THREAD

**Issue by FaigerSYS** [FaigerSYS/superBAR_RUS#2]
Здесь флудим и пишем свои сообщения. Новые записи создавайте только в случае новых идей или ошибок. Также следите за тем, что-бы не создать дубликат!!!

**Comment by opkiler22789** [comment]
у вас есть лого superBar 96x96?

**Comment by FaigerSYS** [comment]
@opkiler22789, есть. Зачем вам? -_-

**Comment by opkiler22789** [comment]
на форум иконку
