### ISSUE TITLE
Больше возможностей

### ISSUE THREAD

**Issue by XakerS** [FaigerSYS/superBAR_RUS#4]
Короче шоб выводил кол-во сломанных&поставленных+время в сессии,време общее.

**Comment by alex2534alex** [comment]
?? Что значит време общие? Грамматика плиз, и больше объяснений...

**Comment by FaigerSYS** [comment]
Зак

**Comment by XakerS** [comment]
Да блять,тябе трудно добавить?)0))
Просто добавь и все!

**Comment by FaigerSYS** [comment]
Ок. Но что ты имел ввиду под общим временем?

**Comment by FaigerSYS** [comment]
@XakerS , ответь

**Comment by XakerS** [comment]
Общие время в игру
Время за 1 сессию,т.е когда зашел будет начат отсчет
Кол-во сломанных блоков + поставленных
